### ISSUE TITLE
Unable to find nodes after installation

### ISSUE THREAD

**Issue by brayevalerien** [get-salt-AI/SaltAI_AudioViz#1]
After installing the extension, I cannot seem to find the nodes. 
![image](https://github.com/get-salt-AI/SaltAI_AudioViz/assets/60972074/914d4220-21c8-49fd-a334-e966eca21563)
Note that I'm trying to find the "Load Audio" node here, but the other nodes from the extension seem to be all missing.

I've tried both installation methods (ComfyUI Manager and manually Git clone and then installing the requirements) even though they should be equivalent.

I'm using the integrated version of ComfyUI (not standalone version) on Windows, with Python 3.10.9 in a Conda environment dedicated to ComfyUI.

**Comment by WAS-PlaiLabs** [comment]
Can you please provide your console log for review? It's likely there is some error hidden away in there.

**Comment by brayevalerien** [comment]
Hello, thanks for answering. After this time, the issue seams to be resolved, probably by an update of ComfyUI or any other extension that happened?
Unfortunatly I don't don't have the logs of when the issue was happening anymore.
